### ISSUE TITLE
 Failure to pick up the correct axis labels if using xlab() and ylab()

### ISSUE THREAD

**Issue by boringNectarine0** [ajrgodfrey/BrailleR#30]
If BrailleR is loaded after the tidyverse functions xlab() and ylab() also do not work on the graph. In the start up notes it mentions "The following objects are masked from ‘package:ggplot2’: xlab, ylab" which suggests that these are used for a different purpose in BrailleR and may need re-naming throughout to be compatible.

**Comment by ajrgodfrey** [comment]
OK, let’s rename the BrailleR functions. I think they are so seldom used that it won’t matter. Perhaps XLab and YLab. Using upper camel case is a habit in BrailleR because camel case reads well in synthetic speech as compared to snake case. N.B. let’s not rename the arguments to the UpdateGraph() function though.

I checked that the functions are not methods; I think not. (that might have been a better path to follow.)

**Comment by ajrgodfrey** [comment]
renamed functions xlab() and ylab() to XLab() and YLab().
