### ISSUE TITLE
No acknowledgement of the difference between geom_point() and geom_jitter()

### ISSUE THREAD

**Issue by boringNectarine0** [ajrgodfrey/BrailleR#34]
When making a scatter graph using ggplot, geom_point() will often not be able to show all the points, particularly if the variables are all integers. VI() will say that there are the total number of points when they aren't truly being displayed by geom_point(). The exact same description is given by by VI() when geom_jitter() has been used, which does display all the points, although slightly offset to where they actually lie.

**Comment by boringNectarine0** [comment]
Fixed by positioning when there is a categorical variable. An exception will need to be made in the conditionals for allowing basic geomJitter types through.

**Comment by 1jamesthompson1** [comment]
The information could be conveyed in a percentage of visible points.

So that a graph like this:
```
ggplot(midwest, aes(area, poptotal)) +
  geom_point(size = 0.5)
```
Could be summarised like this:
> This is an untitled chart with no subtitle or caption.
It has x-axis 'area' with labels 0.00, 0.03, 0.06 and 0.09.
It has y-axis 'poptotal' with labels 0e+00, 1e+06, 2e+06, 3e+06, 4e+06 and 5e+06.
The chart is a set of 437 big solid circle points of which about 57% can be seen individually.
It has size set to 0.5.

This is achieved with something like this:
```
#Get the number of points that can be individually seen
#This will help for users to tell how much overlap there really is
.getGGVisiblePoints = function(cleanData) {
  #Get grid for points to be put into
  roundedPoints = list()
  for (axis in c('x', 'y')) {
    data = cleanData[axis]
    range = max(data) - min(data)
    avgPointSize = mean(cleanData$size)
    #This will get the width of each cell in the grid
    multi = (1/100) * (avgPointSize/1.5) * range
    roundedPoints[axis] = multi * round(data/multi)
  }
  #Return number of indiviual points
  numberOfVisiblePoints = data.frame(roundedPoints) |> distinct() |> nrow()
  numberOfPoints = length(roundedPoints$x)
  (numberOfVisiblePoints / numberOfPoints)
}
```
It splits the graph space into a grid and then works out how many distinct grids there are.

The only catch-up with it at the moment is how big should the grid cell be. It is linked to the point size but I can't find/think of a way to relate the two that would accurately approximate the visible points.
It is this line `(1/100) * (avgPointSize/1.5) * range`

**Comment by ajrgodfrey** [comment]
This sounds promising.

It has opportunity for cosmetic enhancement chosen by the user, jitter or point size reduction as two possible starters.

The benefit if jittering only comes through if there is room for the points to move without bumping others. Knowing how much white space there is might help determine that chance of success.
