### ISSUE TITLE
No indication of what type of graph is shown if it is one that VI() cannot process

### ISSUE THREAD

**Issue by boringNectarine0** [ajrgodfrey/BrailleR#36]
In general for types of graphs that VI() cannot process, at least give the name of the graph eg. ("This density graph is a type which VI() cannot fully process" for geom_density, "This area graph is a type which VI() cannot fully process" for geom_area)
If this can be generalized it will add some information without fully incorporating these rarer graph types.

**Comment by ajrgodfrey** [comment]
Good idea.

**Comment by boringNectarine0** [comment]
Would you have an idea of where I should look to start implementing this?

**Comment by ajrgodfrey** [comment]
There is a series of else if() for the different geom_blah layers. We’ll need something added there as well as making sure something gets reported. This future proofs the code so that if something can be developed for the various layer types, that we know where to add things in.

We might then need to think about where/how the added information gets returned.

**Comment by boringNectarine0** [comment]
Done in pull request #40.
